/**
 * 
 */
 
 define(function(require,exports,module){
 	return {
 		member_tpl:['<div class="subsection">',
 						'<div class="cmp-class">',
 							'<h3 class="component"><a class="class-source-link" href="#"><%=name%></a></h3>',
 						'</div>',
 						'<div class="doc-contents">',
 							'<%=desc%>',
 						'</div>',
 						'<% _.each(members,function(rec){ %>',
	 					'<div class="member inherited" id="method-addChildEls" style="display: block;">',
	 						'<a class="side expandable" href="#"><span>&nbsp;</span></a>',
	 						'<div class="title">',
	 							'<a class="name expandable" href="#"><%= rec.name %></a>',
	 							'( <span class="pre"><% var recs =rec.params,len=recs.length-1;  _.each(recs,function(r,index){print( !!r.optional?("["+r.name +"]"):r.name + (index==len?"":", ")) }) %></span> )',
	 						'</div>',
	 						'<div class="description">',
	 							'<div class="short"><% print(Ambow.ellipsis(rec.desc,40,true)) %></div>',
	 							'<div class="long">',
	 								'<p><%= rec.desc %></p>',
	 								'<h5 class="pa">Parameters</h5>',
	 								'<ul>',
	 									'<% _.each(rec.params,function(r){ %>',
	 									'<li>',
	 										'<span class="pre"><%= r.name %></span> : <a href="#"><%= r.type %></a>',
	 										'<div class="sub-desc"><p><%= r.desc %></p></div>',
	 									'</li>',
	 									'<% }) %>',
	 								'</ul>',
	 								'<% if(rec.back){ %>',
	 								'<h5 class="pa">Returns</h5>',
	 								'<ul>',
	 									'<li>',
	 										'<span class="pre"><a href="#"><%= rec.back.type %></a>',
	 										'<div class="sub-desc"><p><%= rec.back.desc %></p></div>',
	 									'</li>',
	 								'</ul>',
	 								'<% } %>',
	 								'<% var codes = rec.code; if(codes) {%>',
	 								'<div>',
	 									'<% _.each(codes,function(r){ %>',
	 									'<div class="code-section">',
	 										'<pre>',
	 											'<%= r.code %>',
	 										'</pre>',
	 										'<input type="button" value="<%=r.name%>" class="run">',
	 									'</div>',
	 									'<% }) %>',
	 								'</div>',
	 								'<% } %>',
	 							'</div>',
	 						'</div>',
	 					'</div>',
	 					'<% }) %>',
 					'</div>'].join('')
 	}
 });